[2024-06-20T11:35:20.467+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-20T11:35:20.483+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_data_etl_v30.data_etl.parse_data.parse_data scheduled__2024-06-19T12:00:00+00:00 [queued]>
[2024-06-20T11:35:20.488+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_data_etl_v30.data_etl.parse_data.parse_data scheduled__2024-06-19T12:00:00+00:00 [queued]>
[2024-06-20T11:35:20.489+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-20T11:35:20.497+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_etl.parse_data.parse_data> on 2024-06-19 12:00:00+00:00
[2024-06-20T11:35:20.502+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_data_etl_v30', 'data_etl.parse_data.parse_data', 'scheduled__2024-06-19T12:00:00+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/data_etl_dag.py', '--cfg-path', '/tmp/tmpx73bn3_g']
[2024-06-20T11:35:20.504+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1050) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-20T11:35:20.506+0000] {standard_task_runner.py:91} INFO - Job 130: Subtask data_etl.parse_data.parse_data
[2024-06-20T11:35:20.506+0000] {standard_task_runner.py:63} INFO - Started process 1055 to run task
[2024-06-20T11:35:20.533+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_data_etl_v30.data_etl.parse_data.parse_data scheduled__2024-06-19T12:00:00+00:00 [running]> on host 10482076056f
[2024-06-20T11:35:20.583+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Solarev Ruslan' AIRFLOW_CTX_DAG_ID='dag_data_etl_v30' AIRFLOW_CTX_TASK_ID='data_etl.parse_data.parse_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-19T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-19T12:00:00+00:00'
[2024-06-20T11:35:20.585+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-20T11:35:20.585+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-20T11:35:20.586+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/parse_hh.py", line 211, in get_dataset_with_tags
    professions = ti.pull_xcom(task_ids="get_professions", key="professions")
                  ^^^^^^^^^^^^
AttributeError: 'TaskInstance' object has no attribute 'pull_xcom'
[2024-06-20T11:35:20.595+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_data_etl_v30, task_id=data_etl.parse_data.parse_data, run_id=scheduled__2024-06-19T12:00:00+00:00, execution_date=20240619T120000, start_date=20240620T113520, end_date=20240620T113520
[2024-06-20T11:35:20.603+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 130 for task data_etl.parse_data.parse_data ('TaskInstance' object has no attribute 'pull_xcom'; 1055)
[2024-06-20T11:35:20.639+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-20T11:35:20.648+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-20T11:35:20.652+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
