[2024-06-12T01:13:32.759+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_data_etl3.print_hello scheduled__2024-01-05T12:00:00+00:00 [queued]>
[2024-06-12T01:13:32.768+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_data_etl3.print_hello scheduled__2024-01-05T12:00:00+00:00 [queued]>
[2024-06-12T01:13:32.768+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2024-06-12T01:13:32.785+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): print_hello> on 2024-01-05 12:00:00+00:00
[2024-06-12T01:13:32.790+0000] {standard_task_runner.py:57} INFO - Started process 272 to run task
[2024-06-12T01:13:32.792+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_data_etl3', 'print_hello', 'scheduled__2024-01-05T12:00:00+00:00', '--job-id', '1028', '--raw', '--subdir', 'DAGS_FOLDER/data_etl_dag.py', '--cfg-path', '/tmp/tmpinsvi7p7']
[2024-06-12T01:13:32.795+0000] {standard_task_runner.py:85} INFO - Job 1028: Subtask print_hello
[2024-06-12T01:13:32.830+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_data_etl3.print_hello scheduled__2024-01-05T12:00:00+00:00 [running]> on host 20b5189d1271
[2024-06-12T01:13:32.879+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Solarev Ruslan' AIRFLOW_CTX_DAG_ID='dag_data_etl3' AIRFLOW_CTX_TASK_ID='print_hello' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T12:00:00+00:00'
[2024-06-12T01:13:32.880+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-06-12T01:13:32.883+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo "hello world" > /opt/***/data/hello.txt']
[2024-06-12T01:13:32.890+0000] {subprocess.py:86} INFO - Output:
[2024-06-12T01:13:32.891+0000] {subprocess.py:93} INFO - /bin/bash: line 1: /opt/***/data/hello.txt: No such file or directory
[2024-06-12T01:13:32.892+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-06-12T01:13:32.898+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-06-12T01:13:32.901+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_data_etl3, task_id=print_hello, execution_date=20240105T120000, start_date=20240612T011332, end_date=20240612T011332
[2024-06-12T01:13:32.912+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1028 for task print_hello (Bash command failed. The command returned a non-zero exit code 1.; 272)
[2024-06-12T01:13:32.924+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-06-12T01:13:32.985+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
