[2024-06-20T22:52:29.754+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-20T22:52:29.770+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_data_etl_v48.data_etl.parse_data.parse_data scheduled__2024-06-20T00:00:00+00:00 [queued]>
[2024-06-20T22:52:29.775+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_data_etl_v48.data_etl.parse_data.parse_data scheduled__2024-06-20T00:00:00+00:00 [queued]>
[2024-06-20T22:52:29.775+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-20T22:52:29.783+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_etl.parse_data.parse_data> on 2024-06-20 00:00:00+00:00
[2024-06-20T22:52:29.788+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_data_etl_v48', 'data_etl.parse_data.parse_data', 'scheduled__2024-06-20T00:00:00+00:00', '--job-id', '220', '--raw', '--subdir', 'DAGS_FOLDER/data_etl_dag.py', '--cfg-path', '/tmp/tmptmpd1lsv']
[2024-06-20T22:52:29.789+0000] {standard_task_runner.py:91} INFO - Job 220: Subtask data_etl.parse_data.parse_data
[2024-06-20T22:52:29.790+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1977) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-20T22:52:29.790+0000] {standard_task_runner.py:63} INFO - Started process 1979 to run task
[2024-06-20T22:52:29.814+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_data_etl_v48.data_etl.parse_data.parse_data scheduled__2024-06-20T00:00:00+00:00 [running]> on host 10482076056f
[2024-06-20T22:52:29.867+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Solarev Ruslan' AIRFLOW_CTX_DAG_ID='dag_data_etl_v48' AIRFLOW_CTX_TASK_ID='data_etl.parse_data.parse_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-20T00:00:00+00:00'
[2024-06-20T22:52:29.867+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-20T22:52:29.868+0000] {logging_mixin.py:188} INFO - None
[2024-06-20T22:52:29.879+0000] {logging_mixin.py:188} INFO - Добавлена новая профессия: N
[2024-06-20T22:52:51.007+0000] {logging_mixin.py:188} INFO - Добавлена новая профессия: o
[2024-06-20T22:53:11.901+0000] {logging_mixin.py:188} INFO - Добавлена новая профессия: n
[2024-06-20T22:53:15.126+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-06-20T22:53:15.126+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-20T22:53:15.127+0000] {process_utils.py:132} INFO - Sending 15 to group 1979. PIDs of all processes in the group: [1979]
[2024-06-20T22:53:15.128+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 1979
[2024-06-20T22:53:15.128+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-20T22:53:15.128+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-20T22:53:15.132+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/parse_hh.py", line 227, in get_dataset_with_tags
    prof_df = get_prof_tags(profession, max_row_count, card_type, existing_links)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/parse_hh.py", line 193, in get_prof_tags
    tags = get_tags(link, card_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/parse_hh.py", line 142, in get_tags
    res = requests.get(
          ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-06-20T22:53:15.137+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_data_etl_v48, task_id=data_etl.parse_data.parse_data, run_id=scheduled__2024-06-20T00:00:00+00:00, execution_date=20240620T000000, start_date=20240620T225229, end_date=20240620T225315
[2024-06-20T22:53:15.154+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1979, status='terminated', exitcode=2, started='22:52:28') (1979) terminated with exit code 2
