[2024-06-20T12:00:00.868+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-20T12:00:00.884+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_data_etl_v31.data_etl.parse_data.get_professions scheduled__2024-06-20T00:00:00+00:00 [queued]>
[2024-06-20T12:00:00.888+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_data_etl_v31.data_etl.parse_data.get_professions scheduled__2024-06-20T00:00:00+00:00 [queued]>
[2024-06-20T12:00:00.889+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-20T12:00:00.896+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_etl.parse_data.get_professions> on 2024-06-20 00:00:00+00:00
[2024-06-20T12:00:00.901+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_data_etl_v31', 'data_etl.parse_data.get_professions', 'scheduled__2024-06-20T00:00:00+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/data_etl_dag.py', '--cfg-path', '/tmp/tmp6st583d6']
[2024-06-20T12:00:00.902+0000] {standard_task_runner.py:91} INFO - Job 145: Subtask data_etl.parse_data.get_professions
[2024-06-20T12:00:00.903+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2846) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-20T12:00:00.904+0000] {standard_task_runner.py:63} INFO - Started process 2848 to run task
[2024-06-20T12:00:00.927+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_data_etl_v31.data_etl.parse_data.get_professions scheduled__2024-06-20T00:00:00+00:00 [running]> on host 10482076056f
[2024-06-20T12:00:00.968+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Solarev Ruslan' AIRFLOW_CTX_DAG_ID='dag_data_etl_v31' AIRFLOW_CTX_TASK_ID='data_etl.parse_data.get_professions' AIRFLOW_CTX_EXECUTION_DATE='2024-06-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-20T00:00:00+00:00'
[2024-06-20T12:00:00.969+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-20T12:00:00.969+0000] {get_professions.py:8} INFO - Got the list of professions
[2024-06-20T12:00:00.970+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-20T12:00:00.970+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/get_professions.py", line 10, in get_professions
    ti.push_xcom(key="professions", value=professions)
    ^^^^^^^^^^^^
AttributeError: 'TaskInstance' object has no attribute 'push_xcom'
[2024-06-20T12:00:00.978+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_data_etl_v31, task_id=data_etl.parse_data.get_professions, run_id=scheduled__2024-06-20T00:00:00+00:00, execution_date=20240620T000000, start_date=20240620T120000, end_date=20240620T120000
[2024-06-20T12:00:00.988+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 145 for task data_etl.parse_data.get_professions ('TaskInstance' object has no attribute 'push_xcom'; 2848)
[2024-06-20T12:00:00.997+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-20T12:00:01.010+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-20T12:00:01.013+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
